enum Status {
  P
  AP
  L
  A
}

type Attendance {
  session: String!
  status: Status!
  student_id: ID!
  marker: String!
}

type AttendanceReturnStatuses {
  P: Int!
  AP: Int!
  L: Int!
  A: Int!
  total: Int!
}

type Query {
  countAttendanceByClass(className: String!): AttendanceReturnStatuses
  countAttendanceByStudent(studentId: ID!): AttendanceReturnStatuses
}

type Mutation {
  markAttendance(session: String!, status: Status!, studentId: ID!, marker: String!): Attendance
  removeAttendance(studentId: ID!, session: String!): Boolean
}